### ISSUE TITLE
Compilation errors in typescript type definition?

### ISSUE THREAD

**Issue by Moulde** [jcubic/jquery.terminal#425]
### Expected behavior
That everything compiles in my angular 6 application.

### Actual behavior
I get the following error after upgrading from v1.12.1 to v1.21.0

`ERROR in node_modules/jquery.terminal/js/jquery.terminal.d.ts(324,54): error TS2344: Type 'TElement' does not satisfy the constraint 'Node'.
node_modules/jquery.terminal/js/jquery.terminal.d.ts(363,38): error TS2344: Type 'TElement' does not satisfy the constraint 'EventTarget'.
node_modules/jquery.terminal/js/jquery.terminal.d.ts(364,42): error TS2344: Type 'TElement' does not satisfy the constraint 'EventTarget'.
node_modules/jquery.terminal/js/jquery.terminal.d.ts(439,65): error TS2344: Type 'TElement' does not satisfy the constraint 'Node'.
node_modules/jquery.terminal/js/jquery.terminal.d.ts(465,41): error TS2344: Type 'TElement' does not satisfy the constraint 'EventTarget'.
node_modules/jquery.terminal/js/jquery.terminal.d.ts(467,38): error TS2344: Type 'TElement' does not satisfy the constraint 'EventTarget'.
node_modules/jquery.terminal/js/jquery.terminal.d.ts(487,38): error TS2344: Type 'TElement' does not satisfy the constraint 'EventTarget'.
node_modules/jquery.terminal/js/jquery.terminal.d.ts(488,42): error TS2344: Type 'TElement' does not satisfy the constraint 'EventTarget'.
node_modules/jquery.terminal/js/jquery.terminal.d.ts(500,38): error TS2344: Type 'TElement' does not satisfy the constraint 'EventTarget'.
node_modules/jquery.terminal/js/jquery.terminal.d.ts(501,42): error TS2344: Type 'TElement' does not satisfy the constraint 'EventTarget'.`

### Browser and OS
Angular CLI: 6.1.3
Node: 8.11.3
OS: darwin x64
Angular: 6.1.1

**Comment by jcubic** [comment]
which version of typescript anf jquery lib and @types do you use? Do you have this project somewhere where I can check?

**Comment by Moulde** [comment]
Typescript: 2.9.2
jQuery: 3.3.1

I don't have any @types for jquery.terminal installed. I get the above errors just from installing the new version of the package and importing it in my typescript file.
The project is not public, but I'll see if I can reproduce the issue in a stackblitz or new ang application.

**Comment by jcubic** [comment]
from version 1.19.0 the package include typings, maybe there is something in your code, do you use any `any` to make terminal work with typescript?

**Comment by jcubic** [comment]
do you have `@types/jquery` installed? that's required in typescript.

**Comment by jcubic** [comment]
If you have `@types/jquery` try to update it.

**Comment by Moulde** [comment]
I updated the @types/jquery to the most recent version, and now everything is good. Thanks!
Now i just have to update my code to use the new types as it seems like there are some differences.
Like setting the prompt using set_prompt does now take a ExtendedPrompt instead of a string.
Do you have any usage examples?

(btw, it seems like the greetings property is missing from the TerminalOptions type?)

**Comment by jcubic** [comment]
prompt was a bug it should be:

```
type ExtendedPrompt = ((this: JQueryTerminal, setPrompt: setStringFunction) => (void | PromiseLike<string>)) | string;
```

I thought that `| string` was function or string and it was function that returns void, promise or string.

**Comment by jcubic** [comment]
I thought that typescript d.ts file is complete but it still need work like echo value can be string, array of strings or function that return string or array and any promise that is passed to echo like the one in prompt can resolve to the same value.

so if fact this should be
```
type echoValue = string | string[] | (() => string | string[]);
type ExtendedPrompt = ((this: JQueryTerminal, setPrompt: setStringFunction) => (void | PromiseLike<echoValue>)) | string;
```

**Comment by Moulde** [comment]
@jcubic So right now keeping the type definition up to date is a seperate task, which is hard to verify besides having a complete usage example to build? Is the only way to avoid this, to rewrite everything in typescript, which i think would be an enormous task, or is there other preferably automated ways?

Anyway, I will keep this in mind and see if I can contribute to the type definitions at some point.

**Comment by jcubic** [comment]
I will add typescript as dev dependency and I will run tsc on test.ts file on build, that will be compete api usage in one file, it will not be that big, spec file (__test__ directory) that test the library will be much bigger. I think that typescript definition will be more complex then api usage.

**Comment by jcubic** [comment]
I've updated d.ts file with all related to terminal cmd still need testing.

**Comment by jcubic** [comment]
Version 1.22.0 with updated d.ts file just got released.
