### ISSUE TITLE
TS2315: Type 'Event' is not generic.

### ISSUE THREAD

**Issue by peterorts** [jcubic/jquery.terminal#492]
I've upgraded to latest version:
"jquery.terminal": "^2.5.0",

But seeing the following errors:

``ERROR in node_modules/jquery.terminal/js/jquery.terminal.d.ts(403,86): error TS2315: Type 'Event' is not generic.``
``node_modules/jquery.terminal/js/jquery.terminal.d.ts(404,83): error TS2315: Type 'Event' is not generic.``
``node_modules/jquery.terminal/js/jquery.terminal.d.ts(531,82): error TS2315: Type 'Event' is not generic.``
``node_modules/jquery.terminal/js/jquery.terminal.d.ts(531,82): error TS2315: Type 'Event' is not generic.``
``node_modules/jquery.terminal/js/jquery.terminal.d.ts(531,82): error TS2315: Type 'Event' is not generic.``

This is my versions:
"jquery": "^3.4.1",
"@types/jquery": "^3.3.29",
"typescript": "~2.9.2",

I'm assuming something needs to be upgraded. Any suggestions to what? 
Thanks.

**Comment by jcubic** [comment]
Latest typescript is 3.4 not sure if it will work with `2.9` can you test if upgrading typescript fix the issue. The repo don't include typescript because it only use it to test type checking, and users may don't use typescript.

**Comment by jcubic** [comment]
Or maybe the issue is jQuery 3.4 will check later today.

**Comment by jcubic** [comment]
the problem is `@types/jquery` they made breaking change without changing version to `4.x.x` it works with version `3.3.6`

**Comment by jcubic** [comment]
The problem is that in jQuery Terminal I use same names as in jQuery I use inherit from JQuery and overwrite the function but because of TypeScript I need to write same signature for original function from jQuery and those changed, they don't affect code that use jQuery but if affect jQuery Terminal (because terminal instance of jQuery object with additional methods) and it will break the code each time they change the signature of overwritten functions.

Will update the typescript definition and set fixed version of @types/jquery, I hope this will not break other peoples code in the future.

**Comment by peterorts** [comment]
We've downgraded to types version 3.3.6, that seems to work.

Thank you for addressing this.

And thank you for a very cool project. Keep up the good work :-)

**Comment by jcubic** [comment]
The types got fixed and the version of types got freezed.
